<a href="https://colab.research.google.com/github/yeojeong735/2025-1-BD/blob/main/inclass/02w_0317_pandas_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 시리즈 활용

In [3]:
import numpy as np
import pandas as pd

s = {'희빈', '수영', '지민', '유정'}
p = pd.Series([99,48,64,84], index=s)

p

수영    99
유정    48
지민    64
희빈    84
dtype: int64

In [5]:
p.name = '수학성적'
p.index.name = '이름'
p

이름
수영    99
유정    48
지민    64
희빈    84
Name: 수학성적, dtype: int64

In [8]:
p.sort_index(ascending=False) #오름차순

이름
희빈    84
지민    64
유정    48
수영    99
Name: 수학성적, dtype: int64

In [9]:
p.sort_values()

이름
유정    48
지민    64
희빈    84
수영    99
Name: 수학성적, dtype: int64

In [10]:
p.sort_values(ascending=False) #오름차순

이름
수영    99
희빈    84
지민    64
유정    48
Name: 수학성적, dtype: int64

## 시리즈 기본 통계 함수

In [12]:
print(p.max())
print(p.min())
print(p.median())
print(p.mean())
print(p.count())
print(p.size)

99
48
74.0
73.75
4
4

In [13]:
p.describe()

count     4.000000
mean     73.750000
std      22.366269
min      48.000000
25%      60.000000
50%      74.000000
75%      87.750000
max      99.000000
Name: 수학성적, dtype: float64

In [16]:
s = pd.Series([3,1,1,2,None,np.nan,4,6,6,np.nan])
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [17]:
s.values

array([ 3.,  1.,  1.,  2., nan, nan,  4.,  6.,  6., nan])

In [18]:
s.count()

7

In [19]:
s.value_counts()

1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [20]:
s.value_counts(dropna=False)

NaN    3
1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [21]:
s.value_counts(dropna=False, sort=False)

3.0    1
1.0    2
2.0    1
NaN    3
4.0    1
6.0    2
Name: count, dtype: int64

In [22]:
s.value_counts(bins=4)

(0.994, 2.25]    3
(4.75, 6.0]      2
(2.25, 3.5]      1
(3.5, 4.75]      1
Name: count, dtype: int64

In [24]:
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [23]:
s.value_counts(bins=4, sort=False)

(0.994, 2.25]    3
(2.25, 3.5]      1
(3.5, 4.75]      1
(4.75, 6.0]      2
Name: count, dtype: int64

In [25]:
s.value_counts(bins=[0.5,3.5,6.5], sort=False)

(0.499, 3.5]    4
(3.5, 6.5]      3
Name: count, dtype: int64

## 데이터프레임 기초

In [26]:
df = pd.DataFrame([10,20,30,40,50])
df

    0
0  10
1  20
2  30
3  40
4  50

In [27]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df = pd.DataFrame([[1,2,3],[10,20,30],[100,200,300]], index= list('abc'))
df

     0    1    2
a    1    2    3
b   10   20   30
c  100  200  300

In [30]:
df = pd.DataFrame([[1,2,3],[10,20,30],[100,200,300]], index= list('abc'), columns=['A','B','C'])
df

     A    B    C
a    1    2    3
b   10   20   30
c  100  200  300

In [31]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [32]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [33]:
df1 = pd.DataFrame(data=np.arange(12).reshape(3,4))
df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [37]:
# np.random.seed(100)
df1 = pd.DataFrame(data=np.random.randint(1,46,(5,6)))
df1

    0   1   2   3   4   5
0   5  28   4   8   2  15
1   8  17   3  42  31  20
2  35  28  31  40  39  45
3  19   1  35  11  18   9
4  14  43  31  18   5  41

In [39]:
df1 = pd.DataFrame(data=np.random.random(7,3))
df1

TypeError: random() takes at most 1 positional argument (2 given)

In [44]:
df = pd.DataFrame({'numbers':[1,2,3],'colors':['red','green','blue']})
df

   numbers colors
0        1    red
1        2  green
2        3   blue

In [41]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [42]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [46]:
df = pd.DataFrame({'국어':[100,54,68]},'수학':[54,68,94]},index=['a'.'v','d'])
df

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (<ipython-input-46-f97c7db7e3ec>, line 1)

In [49]:
courses = pd.Series(["spark","pyspark","hadoop"],name='courses')
courses

0      spark
1    pyspark
2     hadoop
Name: courses, dtype: object

In [50]:
fees = pd.Series([256,486,347],name='fees')
fees

0    256
1    486
2    347
Name: fees, dtype: int64

In [52]:
df = pd.DataFrame({courses.name:courses,fees.name:fees})
df

   courses  fees
0    spark   256
1  pyspark   486
2   hadoop   347